# Generated by Django 3.2.12 on 2022-02-25 06:51

from django.db import migrations, models
import django.db.models.deletion
import repository.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=369)),
                ('course_name', models.CharField(max_length=369)),
                ('semester', models.CharField(max_length=369)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=369, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=369)),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=33)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=369)),
                ('course_name', models.CharField(max_length=369)),
                ('course_description', models.TextField(help_text='About the course / files atched to this course')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=repository.models.CourseMaterial.upload_to_thumb_dir)),
                ('semester', models.CharField(choices=[('1', 'Freshman 1st'), ('2', 'Freshman 2nd'), ('3', 'Sophomore 1st'), ('4', 'Sophomore 2nd'), ('5', 'Junior 1st'), ('6', 'Junior 2nd'), ('7', 'Senior 1st'), ('8', 'Senior 2nd'), ('9', 'GC 1st'), ('10', 'GC 2nd')], max_length=2)),
                ('created_by', models.CharField(max_length=369)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('short_name', models.CharField(max_length=369)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=369)),
                ('semes_number', models.IntegerField()),
                ('department_in_this_semes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.department')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=369)),
                ('about', models.TextField()),
                ('department', models.ManyToManyField(related_name='school', to='repository.Department')),
            ],
        ),
        migrations.CreateModel(
            name='LecturePPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.FileField(upload_to=repository.models.LecturePPT.upload_to_ppt_dir)),
                ('title', models.CharField(help_text='chapter or specific title related to this file ', max_length=369)),
                ('cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppts', to='repository.coursematerial')),
            ],
        ),
        migrations.CreateModel(
            name='LecturePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=repository.models.LecturePDF.upload_to_pdf_dir)),
                ('title', models.CharField(help_text='chapter or specific title related to this file ', max_length=369)),
                ('cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='repository.coursematerial')),
            ],
        ),
        migrations.CreateModel(
            name='LectureBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to=repository.models.LectureBook.upload_to_books_dir)),
                ('title', models.CharField(help_text='chapter or specific title related to this file ', max_length=369)),
                ('cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='repository.coursematerial')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=repository.models.Image.upload_to_img_dir)),
                ('title', models.CharField(help_text='chapter or specific title related to this file ', max_length=369)),
                ('cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='repository.assignmentexam')),
            ],
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='repository.department'),
        ),
    ]
