# Generated by Django 3.2.12 on 2022-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='department_in_this_semes',
        ),
        migrations.AddField(
            model_name='semester',
            name='school_in_this_semes',
            field=models.ManyToManyField(to='repository.School'),
        ),
    ]
