# Generated by Django 3.2.12 on 2022-02-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20220225_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.semester'),
        ),
    ]
