# Generated by Django 3.2.12 on 2022-02-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_coursematerial_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='created_by',
            field=models.CharField(default='MrPGuy', max_length=369),
        ),
    ]
