# Generated by Django 3.2.12 on 2022-02-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_alter_coursematerial_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='created_by',
            field=models.CharField(blank=True, default='MrPGuy', max_length=369, null=True),
        ),
    ]
