# Generated by Django 3.2.12 on 2022-02-25 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20220225_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester', to='repository.campus'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='created_by',
            field=models.CharField(blank=True, default='MrPGuy', max_length=369),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='repository.department'),
        ),
    ]
