# Generated by Django 3.2.12 on 2022-03-05 07:29

from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_tguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tg_file_id',
            field=models.CharField(default='1851', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='tg_file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturebook',
            name='tg_file_id',
            field=models.CharField(default='1851', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturebook',
            name='tg_file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturepdf',
            name='tg_file_id',
            field=models.CharField(default='1851', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturepdf',
            name='tg_file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lectureppt',
            name='tg_file_id',
            field=models.CharField(default='1851', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureppt',
            name='tg_file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=repository.models.Image.upload_to_img_dir),
        ),
        migrations.AlterField(
            model_name='lecturebook',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to=repository.models.LectureBook.upload_to_books_dir),
        ),
        migrations.AlterField(
            model_name='lecturepdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=repository.models.LecturePDF.upload_to_pdf_dir),
        ),
        migrations.AlterField(
            model_name='lectureppt',
            name='ppt',
            field=models.FileField(blank=True, null=True, upload_to=repository.models.LecturePPT.upload_to_ppt_dir),
        ),
    ]
