# Generated by Django 3.2.12 on 2022-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20220305_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='user_tg_id',
            field=models.CharField(default='594448426', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
