# Generated by Django 3.2.12 on 2022-03-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20220305_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_tg_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
