# Generated by Django 3.2.12 on 2022-04-01 07:25

import cloudinary_storage.storage
from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_alter_tguser_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='contributors',
            field=models.CharField(blank=True, default='', max_length=369),
        ),
        migrations.AddField(
            model_name='lecturebook',
            name='contributors',
            field=models.CharField(blank=True, default='', max_length=369),
        ),
        migrations.AddField(
            model_name='lecturepdf',
            name='contributors',
            field=models.CharField(blank=True, default='', max_length=369),
        ),
        migrations.AlterField(
            model_name='assignmentexam',
            name='course_code',
            field=models.CharField(max_length=369, unique=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course_code',
            field=models.CharField(max_length=369, unique=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course_name',
            field=models.CharField(max_length=369, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tg_file_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturebook',
            name='book',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=repository.models.LectureBook.upload_to_books_dir),
        ),
        migrations.AlterField(
            model_name='lecturebook',
            name='tg_file_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturepdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=repository.models.LecturePDF.upload_to_pdf_dir),
        ),
        migrations.AlterField(
            model_name='lecturepdf',
            name='tg_file_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lectureppt',
            name='ppt',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=repository.models.LecturePPT.upload_to_ppt_dir),
        ),
        migrations.AlterField(
            model_name='lectureppt',
            name='tg_file_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=369, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=369, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semes_number',
            field=models.IntegerField(unique=True),
        ),
    ]
