# Generated by Django 3.2.12 on 2022-04-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20220401_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureppt',
            name='contributors',
            field=models.CharField(blank=True, default='', max_length=369),
        ),
    ]
