# Generated by Django 3.2.12 on 2022-04-01 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_lectureppt_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentexam',
            name='course_code',
            field=models.CharField(max_length=369, unique=True, validators=[django.core.validators.RegexValidator(message='Only uppercase letters and numbers allowed.', regex='^[A-Z0-9]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course_code',
            field=models.CharField(max_length=369, unique=True, validators=[django.core.validators.RegexValidator(message='Only uppercase letters and numbers allowed.', regex='^[A-Z0-9]{3,}$')]),
        ),
    ]
