# Generated by Django 3.2.12 on 2022-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20220401_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGhelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_to_text', models.CharField(blank=True, max_length=369, null=True)),
                ('how_to_media', models.CharField(blank=True, max_length=369, null=True)),
                ('welcome_text', models.CharField(blank=True, max_length=369, null=True)),
                ('welcome_media', models.CharField(blank=True, max_length=369, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
